// <auto-generated />
using DinnerPlanner.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DinnerPlannerContext))]
    [Migration("20260618120238_MultiDishTypesAndDessertType")]
    partial class MultiDishTypesAndDessertType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DinnerPlanner.Api.Models.DishTypeAssignment", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("DishId", "Type");

                    b.ToTable("DishTypeAssignments");

                    b.HasData(
                        new
                        {
                            DishId = 2,
                            Type = "Bowl"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Amount = 1m,
                            Category = "Chicken",
                            Color = "#f6d4b8",
                            IngredientName = "Chicken breast",
                            Price = 89.90m,
                            Unit = "Kilogram"
                        },
                        new
                        {
                            IngredientId = 2,
                            Amount = 1m,
                            Category = "Vegetable",
                            Color = "#f4ead2",
                            IngredientName = "Garlic",
                            Price = 14.90m,
                            Unit = "Piece"
                        },
                        new
                        {
                            IngredientId = 3,
                            Amount = 500m,
                            Category = "Dairy",
                            Color = "#fff7ef",
                            IngredientName = "Greek yogurt",
                            Price = 34.90m,
                            Unit = "Gram"
                        },
                        new
                        {
                            IngredientId = 4,
                            Amount = 1m,
                            Category = "Grain",
                            Color = "#f6f0df",
                            IngredientName = "Rice",
                            Price = 39.90m,
                            Unit = "Kilogram"
                        },
                        new
                        {
                            IngredientId = 5,
                            Amount = 1m,
                            Category = "Fruit",
                            Color = "#f9dc5c",
                            IngredientName = "Lemon",
                            Price = 8.90m,
                            Unit = "Piece"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.KitchenItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("KitchenItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("KitchenItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Description = "Fresh yogurt sauce with garlic and lemon.",
                            Instructions = "Grate the garlic, stir it into yogurt with lemon, and season to taste.",
                            Name = "Garlic yogurt sauce"
                        },
                        new
                        {
                            RecipeId = 2,
                            Description = "Simple chicken bowl with rice and sauce.",
                            Instructions = "Cook rice. Fry chicken until done. Serve with garlic yogurt sauce.",
                            Name = "Chicken rice bowl"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preparation")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeIngredientId = 1,
                            Amount = 200m,
                            IngredientId = 3,
                            Preparation = "Raw",
                            RecipeId = 1,
                            Unit = "Gram"
                        },
                        new
                        {
                            RecipeIngredientId = 2,
                            Amount = 1m,
                            IngredientId = 2,
                            Preparation = "Grated",
                            RecipeId = 1,
                            Unit = "Clove"
                        },
                        new
                        {
                            RecipeIngredientId = 3,
                            Amount = 1m,
                            IngredientId = 5,
                            Preparation = "Raw",
                            RecipeId = 1,
                            Unit = "Tablespoon"
                        },
                        new
                        {
                            RecipeIngredientId = 4,
                            Amount = 200m,
                            IngredientId = 1,
                            Preparation = "Fried",
                            RecipeId = 2,
                            Unit = "Gram"
                        },
                        new
                        {
                            RecipeIngredientId = 5,
                            Amount = 100m,
                            IngredientId = 4,
                            Preparation = "Boiled",
                            RecipeId = 2,
                            Unit = "Gram"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dessert", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Dessert");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dip", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.HasDiscriminator().HasValue("Dip");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Dish");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Chicken rice bowl",
                            RecipeId = 2,
                            Cuisine = "Asian"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Marinade", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.HasDiscriminator().HasValue("Marinade");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Sauce", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.HasDiscriminator().HasValue("Sauce");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Garlic yogurt sauce",
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Side", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.HasDiscriminator().HasValue("Side");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Steamed rice"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.SpiceMix", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.KitchenItem");

                    b.HasDiscriminator().HasValue("SpiceMix");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.DishTypeAssignment", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Dish", "Dish")
                        .WithMany("Types")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.OwnsOne("DinnerPlanner.Api.Models.NutritionFacts", "NutritionPer100", b1 =>
                        {
                            b1.Property<int>("IngredientId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Calories")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("DietaryFiberGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Vitamins")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("NutritionPer100");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.KitchenItem", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
