// <auto-generated />
using System;
using DinnerPlanner.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DinnerPlannerContext))]
    [Migration("20260630163705_AddMealPlanEntries")]
    partial class AddMealPlanEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DinnerPlanner.Api.Models.DishTypeAssignment", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("DishId", "Type");

                    b.ToTable("DishTypeAssignments");

                    b.HasData(
                        new
                        {
                            DishId = 2,
                            Type = "Bowl"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Amount = 1m,
                            Category = "Chicken",
                            Color = "#f6d4b8",
                            IngredientName = "Chicken breast",
                            Price = 89.90m,
                            Unit = "Kilogram"
                        },
                        new
                        {
                            IngredientId = 2,
                            Amount = 1m,
                            Category = "Vegetable",
                            Color = "#f4ead2",
                            IngredientName = "Garlic",
                            Price = 14.90m,
                            Unit = "Piece"
                        },
                        new
                        {
                            IngredientId = 3,
                            Amount = 500m,
                            Category = "Dairy",
                            Color = "#fff7ef",
                            IngredientName = "Greek yogurt",
                            Price = 34.90m,
                            Unit = "Gram"
                        },
                        new
                        {
                            IngredientId = 4,
                            Amount = 1m,
                            Category = "Grain",
                            Color = "#f6f0df",
                            IngredientName = "Rice",
                            Price = 39.90m,
                            Unit = "Kilogram"
                        },
                        new
                        {
                            IngredientId = 5,
                            Amount = 1m,
                            Category = "Fruit",
                            Color = "#f9dc5c",
                            IngredientName = "Lemon",
                            Price = 8.90m,
                            Unit = "Piece"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanEntry", b =>
                {
                    b.Property<int>("MealPlanEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("MealPlanEntryId");

                    b.HasIndex("Date", "Slot")
                        .IsUnique();

                    b.ToTable("MealPlanEntries");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanRecipe", b =>
                {
                    b.Property<int>("MealPlanRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealPlanEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("MealPlanRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("MealPlanEntryId", "SortOrder");

                    b.ToTable("MealPlanRecipes");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasDiscriminator<string>("RecipeType").HasValue("Recipe");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RecipeIngredients", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dessert", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Dessert");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dip", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Dip");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Dish");

                    b.HasData(
                        new
                        {
                            RecipeId = 2,
                            Description = "Simple chicken bowl with rice and sauce.",
                            Instructions = "Cook rice. Fry chicken until done. Serve with garlic yogurt sauce.",
                            Name = "Chicken rice bowl",
                            Cuisine = "Asian"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Sauce", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Sauce");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Description = "Fresh yogurt sauce with garlic and lemon.",
                            Instructions = "Grate the garlic, stir it into yogurt with lemon, and season to taste.",
                            Name = "Garlic yogurt sauce"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Side", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Side");

                    b.HasData(
                        new
                        {
                            RecipeId = 3,
                            Description = "",
                            Instructions = "Rinse rice and steam until tender.",
                            Name = "Steamed rice"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.SpiceMix", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("SpiceMix");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.DishTypeAssignment", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Dish", "Dish")
                        .WithMany("Types")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.OwnsOne("DinnerPlanner.Api.Models.NutritionFacts", "NutritionPer100", b1 =>
                        {
                            b1.Property<int>("IngredientId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Calories")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("DietaryFiberGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Vitamins")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("NutritionPer100");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanRecipe", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.MealPlanEntry", "MealPlanEntry")
                        .WithMany("Recipes")
                        .HasForeignKey("MealPlanEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlanEntry");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeIngredients", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DinnerPlanner.Api.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanEntry", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
