// <auto-generated />
using System;
using DinnerPlanner.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DinnerPlannerContext))]
    [Migration("20260712143108_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DinnerPlanner.Api.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("BrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("CuisineId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cuisines");

                    b.HasData(
                        new
                        {
                            CuisineId = 1,
                            Name = "Korean"
                        },
                        new
                        {
                            CuisineId = 2,
                            Name = "Indian"
                        },
                        new
                        {
                            CuisineId = 3,
                            Name = "Mediterranean"
                        },
                        new
                        {
                            CuisineId = 4,
                            Name = "French"
                        },
                        new
                        {
                            CuisineId = 5,
                            Name = "Norwegian"
                        },
                        new
                        {
                            CuisineId = 6,
                            Name = "Mexican"
                        },
                        new
                        {
                            CuisineId = 7,
                            Name = "Italian"
                        },
                        new
                        {
                            CuisineId = 8,
                            Name = "Japanese"
                        },
                        new
                        {
                            CuisineId = 9,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            CuisineId = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.HasIndex("BrandId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Color = "#f6d4b8",
                            Description = "Lean poultry cut with mild flavor. Useful as the main protein in bowls, salads, soups, and quick pan-fried dinners.",
                            IngredientName = "Chicken breast",
                            Price = 89.90m
                        },
                        new
                        {
                            IngredientId = 2,
                            Color = "#f4ead2",
                            Description = "Aromatic vegetable used to build flavor in sauces, marinades, soups, stir fries, and roasted dishes.",
                            IngredientName = "Garlic",
                            Price = 14.90m
                        },
                        new
                        {
                            IngredientId = 3,
                            Color = "#fff7ef",
                            Description = "Thick cultured dairy product. Works as a base for cold sauces, dressings, marinades, and high-protein breakfasts.",
                            IngredientName = "Greek yogurt",
                            Price = 34.90m
                        },
                        new
                        {
                            IngredientId = 4,
                            Color = "#f6f0df",
                            Description = "Neutral grain that works as a side or base for bowls, curries, stir fries, and meal prep portions.",
                            IngredientName = "Rice",
                            Price = 39.90m
                        },
                        new
                        {
                            IngredientId = 5,
                            Color = "#f9dc5c",
                            Description = "Bright acidic fruit used for sauces, dressings, marinades, desserts, and finishing cooked dishes.",
                            IngredientName = "Lemon",
                            Price = 8.90m
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.IngredientTagAssignment", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId", "Tag");

                    b.ToTable("IngredientTagAssignments");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Tag = "Chicken"
                        },
                        new
                        {
                            IngredientId = 2,
                            Tag = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 3,
                            Tag = "Dairy"
                        },
                        new
                        {
                            IngredientId = 4,
                            Tag = "Grain"
                        },
                        new
                        {
                            IngredientId = 5,
                            Tag = "Fruit"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanEntry", b =>
                {
                    b.Property<int>("MealPlanEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("MealPlanEntryId");

                    b.HasIndex("Date", "Slot")
                        .IsUnique();

                    b.ToTable("MealPlanEntries");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanRecipe", b =>
                {
                    b.Property<int>("MealPlanRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealPlanEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("MealPlanRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("MealPlanEntryId", "SortOrder");

                    b.ToTable("MealPlanRecipes");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasDiscriminator<string>("RecipeType").HasValue("Recipe");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "IngredientId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeIngredientId = 1,
                            Amount = 200m,
                            IngredientId = 3,
                            RecipeId = 1,
                            Unit = "Gram"
                        },
                        new
                        {
                            RecipeIngredientId = 2,
                            Amount = 1m,
                            IngredientId = 2,
                            RecipeId = 1,
                            Unit = "Clove"
                        },
                        new
                        {
                            RecipeIngredientId = 3,
                            Amount = 0.5m,
                            IngredientId = 5,
                            RecipeId = 1,
                            Unit = "Piece"
                        },
                        new
                        {
                            RecipeIngredientId = 4,
                            Amount = 400m,
                            IngredientId = 1,
                            RecipeId = 2,
                            Unit = "Gram"
                        },
                        new
                        {
                            RecipeIngredientId = 5,
                            Amount = 250m,
                            IngredientId = 4,
                            RecipeId = 2,
                            Unit = "Gram"
                        },
                        new
                        {
                            RecipeIngredientId = 6,
                            Amount = 250m,
                            IngredientId = 4,
                            RecipeId = 3,
                            Unit = "Gram"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeTagAssignment", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId", "Tag");

                    b.ToTable("RecipeTagAssignments");

                    b.HasData(
                        new
                        {
                            RecipeId = 2,
                            Tag = "Bowl"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dessert", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Dessert");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dip", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Dip");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.Property<int?>("CuisineId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CuisineId");

                    b.HasDiscriminator().HasValue("Dish");

                    b.HasData(
                        new
                        {
                            RecipeId = 2,
                            Description = "Weeknight bowl with pan-fried chicken, steamed rice, and fresh garlic yogurt sauce. Good as dinner and easy to scale for meal prep.",
                            ImageUrl = "/images/recipes/chicken-rice-bowl.png",
                            Instructions = "Rinse the rice and cook until tender. Slice the chicken breast, season lightly, and fry in a hot pan until cooked through. Spoon rice into bowls, add chicken, and finish with garlic yogurt sauce.",
                            Name = "Chicken rice bowl",
                            CuisineId = 1
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Sauce", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Sauce");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Description = "Cold yogurt sauce with grated garlic and lemon. Best with chicken bowls, grilled meat, roasted vegetables, and rice.",
                            ImageUrl = "/images/recipes/garlic-yogurt-sauce.png",
                            Instructions = "Grate the garlic finely. Stir garlic, lemon juice, and a little lemon zest into the yogurt. Season with salt and let it rest for at least 10 minutes before serving.",
                            Name = "Garlic yogurt sauce"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Side", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("Side");

                    b.HasData(
                        new
                        {
                            RecipeId = 3,
                            Description = "Plain steamed rice for bowls, curries, stir fries, and saucy dishes.",
                            Instructions = "Rinse the rice until the water runs mostly clear. Cook with the correct amount of water, then rest covered for 5 minutes before fluffing.",
                            Name = "Steamed rice"
                        });
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.SpiceMix", b =>
                {
                    b.HasBaseType("DinnerPlanner.Api.Models.Recipe");

                    b.HasDiscriminator().HasValue("SpiceMix");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("DinnerPlanner.Api.Models.NutritionFacts", "NutritionPer100", b1 =>
                        {
                            b1.Property<int>("IngredientId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Calories")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("CarbohydrateGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("DietaryFiberGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("MonounsaturatedFatGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("PolyunsaturatedFatGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("ProteinGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("SaltGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("SaturatedFatGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("UnsaturatedFatGrams")
                                .HasPrecision(8, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Vitamins")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("NutritionPer100");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.IngredientTagAssignment", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany("Tags")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanRecipe", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.MealPlanEntry", "MealPlanEntry")
                        .WithMany("Recipes")
                        .HasForeignKey("MealPlanEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlanEntry");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.RecipeTagAssignment", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Dish", b =>
                {
                    b.HasOne("DinnerPlanner.Api.Models.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cuisine");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Ingredient", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.MealPlanEntry", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("DinnerPlanner.Api.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
